<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'uuid' => Str::uuid(),
                'name' => 'Grand Opening Celebration',
                'start_date' => '2026-02-01',
                'end_date' => '2026-02-07',
                'start_time' => '10:00:00',
                'end_time' => '22:00:00',
                'description' => 'Join us for our grand opening celebration with special performances, giveaways, and exclusive discounts throughout the week!',
                'location' => 'Main Atrium',
                'organizer' => 'Mal Bali Galeria',
                'is_paid' => false,
                'price' => null,
                'target_audience' => 'General',
                'highlights' => 'Live Music, Giveaways',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Valentine\'s Day Special',
                'start_date' => '2026-02-14',
                'end_date' => '2026-02-14',
                'start_time' => '12:00:00',
                'end_time' => '20:00:00',
                'description' => 'Celebrate love with romantic dining experiences, couple activities, and special Valentine\'s Day promotions at participating stores.',
                'location' => 'Garden Area',
                'organizer' => 'Events Team',
                'is_paid' => true,
                'price' => 150000.00,
                'target_audience' => 'Couples',
                'highlights' => 'Romantic Dinner, Live Jazz',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Kids Fun Festival',
                'start_date' => '2026-03-15',
                'end_date' => '2026-03-22',
                'start_time' => '11:00:00',
                'end_time' => '19:00:00',
                'description' => 'A week-long festival featuring fun activities for kids including face painting, magic shows, balloon art, and interactive games.',
                'location' => 'Kids Zone',
                'organizer' => 'Kids World',
                'is_paid' => true,
                'price' => 50000.00,
                'target_audience' => 'Kids',
                'highlights' => 'Magic Show, Face Painting',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Fashion Week Showcase',
                'start_date' => '2026-04-10',
                'end_date' => '2026-04-17',
                'start_time' => '14:00:00',
                'end_time' => '21:00:00',
                'description' => 'Experience the latest fashion trends with runway shows, styling workshops, and exclusive previews from top fashion brands.',
                'location' => 'Main Atrium',
                'organizer' => 'Fashion Indo',
                'is_paid' => false,
                'price' => null,
                'target_audience' => 'Fashion Enthusiasts',
                'highlights' => 'Runway Show, Styling Tips',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Summer Music Festival',
                'start_date' => '2026-06-20',
                'end_date' => '2026-06-21',
                'start_time' => '16:00:00',
                'end_time' => '23:00:00',
                'description' => 'Two days of live music performances featuring local and international artists across multiple genres.',
                'location' => 'Outdoor Arena',
                'organizer' => 'Sound Check',
                'is_paid' => true,
                'price' => 250000.00,
                'target_audience' => 'Youth',
                'highlights' => 'Live Concert, Food Trucks',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Back to School Fair',
                'start_date' => '2026-07-15',
                'end_date' => '2026-07-31',
                'start_time' => '10:00:00',
                'end_time' => '21:00:00',
                'description' => 'Get ready for the new school year with special discounts on school supplies, uniforms, books, and educational materials.',
                'location' => 'East Wing',
                'organizer' => 'Education Dept',
                'is_paid' => false,
                'price' => null,
                'target_audience' => 'Students',
                'highlights' => 'Book Fair, Tech Deals',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Mid-Year Mega Sale',
                'start_date' => '2026-07-01',
                'end_date' => '2026-07-15',
                'start_time' => '10:00:00',
                'end_time' => '22:00:00',
                'description' => 'Massive discounts up to 70% off on fashion, electronics, home goods, and more from all participating stores.',
                'location' => 'Mall Wide',
                'organizer' => 'Mal Bali Galeria',
                'is_paid' => false,
                'price' => null,
                'target_audience' => 'General',
                'highlights' => 'Big Discounts, Flash Sale',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Halloween Spooktacular',
                'start_date' => '2026-10-31',
                'end_date' => '2026-10-31',
                'start_time' => '15:00:00',
                'end_time' => '22:00:00',
                'description' => 'Trick-or-treat around the mall, costume contest, haunted house experience, and spooky decorations throughout.',
                'location' => 'Main Atrium',
                'organizer' => 'Spooky Events',
                'is_paid' => true,
                'price' => 75000.00,
                'target_audience' => 'Kids & Family',
                'highlights' => 'Costume Contest, Haunted House',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Black Friday Deals',
                'start_date' => '2026-11-27',
                'end_date' => '2026-11-29',
                'start_time' => '08:00:00',
                'end_time' => '23:00:00',
                'description' => 'The biggest shopping event of the year with unbeatable deals, doorbuster specials, and exclusive Black Friday offers.',
                'location' => 'Mall Wide',
                'organizer' => 'Mal Bali Galeria',
                'is_paid' => false,
                'price' => null,
                'target_audience' => 'General',
                'highlights' => 'Doorbusters, Extended Hours',
                'is_active' => true,
            ],
            [
                'uuid' => Str::uuid(),
                'name' => 'Christmas Wonderland',
                'start_date' => '2026-12-01',
                'end_date' => '2026-12-25',
                'start_time' => '10:00:00',
                'end_time' => '22:00:00',
                'description' => 'Experience the magic of Christmas with festive decorations, Santa meet & greet, carol performances, and holiday shopping.',
                'location' => 'Central Plaza',
                'organizer' => 'Santa Corp',
                'is_paid' => false,
                'price' => null,
                'target_audience' => 'Family',
                'highlights' => 'Santa Visit, Snow Show',
                'is_active' => true,
            ],
        ];

        foreach ($events as $event) {
            Event::create($event);
        }
    }
}
